### ISSUE TITLE
Is there any method of retrieve ad search performance data without download report?

### ISSUE THREAD

**Issue by mooxiu** [yahoojp-marketing/ads-search-api-documents#9]
Hi, Like the title mentioned, I hope to retrieve some performance metrics like `impressions`, `clicks` without really download a report.

Is there any way of doing that? I did not found any feasible API to achieve that in your API reference.

**Comment by ryfukuda** [comment]
Thank you for your inquiry.
There is currently no way to retrieve performance data for search ads without downloading a report.

Also, please use the following URL for future inquiries.
https://ads-developers.yahoo.co.jp/developercenter/en/faq/inquiry_from_eu.html

Best Regards,
ryfukuda

**Comment by mooxiu** [comment]
> Thank you for your inquiry. There is currently no way to retrieve performance data for search ads without downloading a report.
> 
> Also, please use the following URL for future inquiries. https://ads-developers.yahoo.co.jp/developercenter/en/faq/inquiry_from_eu.html
> 
> Best Regards, ryfukuda

Thank you for replying, I will do.
